### ISSUE TITLE
import Okra from "npm-okrajs" not working

### ISSUE THREAD

**Issue by Lundii** [okraHQ/npm-okrajs#1]
There seems to be an issue with the current Okra build. After installing with npm install npm-okrajs, I tried to import the package into my react project using `import Okra from 'npm-okrajs'`. I got this error `Attempted import error: 'npm-okrajs' does not contain a default export (imported as 'Okra').`

I downgraded to version ^1.0.8 and it works fine.

**Comment by oreace** [comment]
Hi @Lundii 
This has been resolved, 
Please upgrade to 2.0.1 and try again.

Sorry for the inconvenience.
